import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/providers/redux-provider";
import ReactQueryProvider from "@/providers/tanstak-query-provider";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Define weights as needed
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
        className={` ${poppins.className} font-sans h-screen`}
      >
        <body>
            <ReactQueryProvider>
              <StoreProvider>
                {children}
              </StoreProvider>
            </ReactQueryProvider>
        </body>
      </html>
  );
}
